services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    networks:
      default: { }
    ports:
      - "8123:8123"
      - "5678:5678"
    volumes:
      - ./config:/config
      - ../custom_components/comelit:/config/custom_components/comelit
  pytest:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.pytest
    container_name: comelit-pytest
    working_dir: /workspaces/homeassistant-comelit
    volumes:
      - ..:/workspaces/homeassistant-comelit
